export const convos = [{
        id: 0,
        name: "Nash Solon",
        messages: [{
                id: 0,
                text: "Hey, how's it going?",
                time: "10:00 AM",
                fromMe: false,
            },
            {
                id: 1,
                text: "Hey, I'm good, how are you?",
                time: "10:01 AM",
                fromMe: true,
            },
            {
                id: 2,
                text: "I'm good, thanks for asking!",
                time: "10:02 AM",
                fromMe: false,
            },
        ],
    },
    {
        id: 1,
        name: "Nisha Sahgal",
        messages: [{
                id: 0,
                text: "Hey, what's up?",
                time: "10:00 AM",
                fromMe: false,
            },
            {
                id: 1,
                text: "Hey, not much.",
                time: "10:01 AM",
                fromMe: true,
            },
        ],
    },
    {
        id: 2,
        name: "Kyle Montgomery",
        messages: [{
                id: 0,
                text: "Hey, how's it going?",
                time: "10:00 AM",
                fromMe: false,
            },
            {
                id: 1,
                text: "Hey, I'm good, how are you?",
                time: "10:01 AM",
                fromMe: true,
            },
            {
                id: 2,
                text: "I'm good, thanks for asking!",
                time: "10:02 AM",
                fromMe: false,
            },
        ],
    },
    {
        id: 3,
        name: "Carson Brown",
        messages: [{
                id: 0,
                text: "Hey, how's it going?",
                time: "10:00 AM",
                fromMe: false,
            },
            {
                id: 1,
                text: "Hey, I'm good, how are you?",
                time: "10:01 AM",
                fromMe: true,
            },
            {
                id: 2,
                text: "I'm good, thanks for asking!",
                time: "10:02 AM",
                fromMe: false,
            },
        ],
    },
    {
        id: 4,
        name: "Michael Schlaurbaum",
        messages: [{
                id: 0,
                text: "Hey, how's it going?",
                time: "10:00 AM",
                fromMe: false,
            },
            {
                id: 1,
                text: "Hey, I'm good, how are you?",
                time: "10:01 AM",
                fromMe: true,
            },
            {
                id: 2,
                text: "I'm good, thanks for asking!",
                time: "10:02 AM",
                fromMe: false,
            },
        ],
    },
    {
        id: 5,
        name: "Vincent Li",
        messages: [{
                id: 0,
                text: "Hey, how's it going?",
                time: "10:00 AM",
                fromMe: false,
            },
            {
                id: 1,
                text: "Hey, I'm good, how are you?",
                time: "10:01 AM",
                fromMe: true,
            },
            {
                id: 2,
                text: "I'm good, thanks for asking!",
                time: "10:02 AM",
                fromMe: false,
            },
        ],
    },
];